# Generated by Django 5.0.6 on 2026-09-22 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=150)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='employers/logos/')),
                ('company_description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('company_size', models.CharField(choices=[('SOLO', '1 (solo)'), ('SMALL', '2-10'), ('MEDIUM', '11-50'), ('LARGE', '51-200'), ('ENTERPRISE', '200+')], default='SMALL', max_length=20)),
                ('company_website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='freelancer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('professional_title', models.CharField(blank=True, max_length=150)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in your preferred currency.', max_digits=10, null=True)),
                ('availability', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('NOT_AVAILABLE', 'Not available')], default='FULL_TIME', max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('education', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated list of languages.', max_length=255)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured freelancers appear at the top of listings (admin only).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Freelancer Profile',
                'verbose_name_plural': 'Freelancer Profiles',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
