# Generated by Django 5.0.6 on 2026-09-25 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employerprofile_freelancerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Change Request',
                'verbose_name_plural': 'Email Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
