# Generated by Django 5.0.6 on 2026-09-22 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('NEW_APPLICATION', 'New application'), ('APPLICATION_ACCEPTED', 'Application accepted'), ('APPLICATION_REJECTED', 'Application rejected'), ('APPLICATION_WITHDRAWN', 'Application withdrawn'), ('JOB_STATUS_CHANGED', 'Job status changed'), ('NEW_MESSAGE', 'New message'), ('NEW_REVIEW', 'New review'), ('SYSTEM', 'System')], default='SYSTEM', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('related_object_type', models.CharField(blank=True, max_length=40)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
