"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

# # ---------- settings.py ----------
# @'
# """
# Entry point for Django settings.

# Dispatches to config.settings_dev or config.settings_prod based on the
# DJANGO_ENV environment variable. Default is "dev".
# """
# import os

# ENV = os.environ.get("DJANGO_ENV", "dev").lower()

# if ENV == "prod":
#     from .settings_prod import *  # noqa: F401,F403
# elif ENV == "dev":
#     from .settings_dev import *  # noqa: F401,F403
# else:
#     raise ValueError(
#         f"Unknown DJANGO_ENV: {ENV!r}. Set it to 'dev' or 'prod'."
#     )
# '@ | Out-File -Encoding utf8 "config\settings.py"
# Write-Host "settings.py written."

# # ---------- settings_base.py ----------
# @'
# """
# Shared Django settings for dev and prod.
# """
import sys
from datetime import timedelta
from pathlib import Path
from decouple import Csv, config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APPS_DIR = BASE_DIR / "apps"
sys.path.insert(0, str(APPS_DIR))

# Detect the Django test runner. Used to disable throttling during tests
# so that loops over endpoints don't trip 429s and mask the actual
# behavior under test.
IN_TESTS = "test" in sys.argv or "pytest" in sys.argv[0]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tbi=5w+m*dl+1oa3y(38tygr+ak+a7m1_m6=m*_b9lr0byqu!x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="127.0.0.1,localhost",
    cast=Csv(),
)
# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https://freelance-marketplace.*\.vercel\.app$",
# ]

# CORS_ALLOW_CREDENTIALS = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # THIRD_PARTY_APPS
     "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    "drf_spectacular",

    # LOCAL_APPS
    "apps.accounts",
    "apps.categories",
    "apps.jobs",
    "apps.applications",
    "apps.bookmarks",
    "apps.portfolios",
    "apps.reviews",
    "apps.messaging",
    "apps.notifications",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

# ------------------------------------------------------------------
# Upload limits (security)
# ------------------------------------------------------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# ------------------------------------------------------------------
# Django REST Framework
# ------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/minute",
        "user": "240/minute",
        "login": "5/minute",
        "register": "3/hour",
        "password_reset": "3/hour",
        "change_email": "3/hour",
        "change_password": "5/hour",
    },
}

# ------------------------------------------------------------------
# Simple JWT
# ------------------------------------------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=config("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", default=60, cast=int)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=config("JWT_REFRESH_TOKEN_LIFETIME_DAYS", default=7, cast=int)
    ),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ------------------------------------------------------------------
# CORS
# ------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://freelance-marketplace-lac-psi.vercel.app",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://freelance-marketplace.*\.vercel\.app$",
]

CORS_ALLOW_CREDENTIALS = False

# ------------------------------------------------------------------
# Cache (used by DRF throttling)
# ------------------------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "freelance-marketplace",
    }
}

# ------------------------------------------------------------------
# Email
# ------------------------------------------------------------------
# In development, EMAIL_BACKEND is the console backend: any email the
# app sends is printed to the terminal where `runserver` is running.
# In production, set EMAIL_BACKEND, EMAIL_HOST, EMAIL_PORT, etc. via
# .env to use a real SMTP service.
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL", default="Freelance Marketplace <noreply@freelancemarketplace.local>"
)

# The frontend origin used to build links that end up in emails.
# In production this is your real domain.
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:5173")

# How long tokens for email change / password reset remain valid.
EMAIL_CHANGE_TOKEN_LIFETIME_HOURS = config(
    "EMAIL_CHANGE_TOKEN_LIFETIME_HOURS", default=24, cast=int
)
PASSWORD_RESET_TOKEN_LIFETIME_HOURS = config(
    "PASSWORD_RESET_TOKEN_LIFETIME_HOURS", default=2, cast=int
)

# ------------------------------------------------------------------
# Logging
# ------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "drf_spectacular": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# ------------------------------------------------------------------
# Test mode: disable throttling
# ------------------------------------------------------------------
if IN_TESTS:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {}

# ------------------------------------------------------------------
# Production-only security settings
# ------------------------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # SECURE_HSTS_SECONDS = 31536000
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True
    # SECURE_CONTENT_TYPE_NOSNIFF = True
    # SECURE_BROWSER_XSS_FILTER = True
    # X_FRAME_OPTIONS = "DENY"

# ------------------------------------------------------------------
# drf-spectacular (OpenAPI docs)
# ------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    "TITLE": "Freelance Marketplace API",
    "DESCRIPTION": (
        "REST API for the **Freelance & Job Marketplace** platform.\n\n"
        "### Authentication\n"
        "Most write endpoints require a JWT **access token** in the "
        "`Authorization: Bearer <token>` header. Get a token via "
        "`POST /api/auth/login/`. Refresh it via `POST /api/auth/token/refresh/`.\n\n"
        "### Roles\n"
        "- **Freelancer** — creates portfolios, applies to jobs, bookmarks, messages employers.\n"
        "- **Employer** — posts jobs, reviews applications, accepts/rejects freelancers.\n"
        "- **Admin** — manages taxonomy (categories, skills) and platform content.\n\n"
        "### Pagination\n"
        "List endpoints return `{ \"count\": int, \"next\": url|null, "
        "\"previous\": url|null, \"results\": [...] }`."
    ),
    "VERSION": "1.0.0",
    "CONTACT": {"name": "Freelance Marketplace Team", "email": "support@example.com"},
    "LICENSE": {"name": "MIT"},
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api",
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": False,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": False,
        "filter": True,
        "docExpansion": "none",
    },
    "SECURITY": [{"jwtAuth": []}],
    "TAGS": [
        {"name": "auth", "description": "Authentication, registration, and current user."},
        {"name": "profiles", "description": "Freelancer and employer profiles."},
        {"name": "users", "description": "Public user listings and reviews about users."},
        {"name": "categories", "description": "Job categories (admin-managed)."},
        {"name": "skills", "description": "Skill tags for jobs, freelancers, and portfolios."},
        {"name": "jobs", "description": "Job postings — create, browse, search, filter."},
        {"name": "applications", "description": "Freelancers apply; employers accept or reject."},
        {"name": "bookmarks", "description": "Saved jobs."},
        {"name": "portfolios", "description": "Freelancer portfolio projects and images."},
        {"name": "reviews", "description": "Mutual ratings after a completed job."},
        {"name": "messaging", "description": "Conversations and messages."},
        {"name": "notifications", "description": "In-app notification feed."},
    ],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "Paste your access token here. Do not include the word 'Bearer'.",
            }
        }
    },
}