# Generated by Django 5.0.6 on 2026-09-22 01:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('budget_type', models.CharField(choices=[('FIXED_PRICE', 'Fixed Price'), ('HOURLY', 'Hourly')], default='FIXED_PRICE', max_length=20)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('experience_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('remote_status', models.CharField(choices=[('ONSITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='REMOTE', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='categories.category')),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'EMPLOYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='jobs', to='categories.skill')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='jobs_job_status_57b86b_idx'), models.Index(fields=['category', 'status'], name='jobs_job_categor_2e2729_idx'), models.Index(fields=['employer', '-created_at'], name='jobs_job_employe_3635f7_idx')],
            },
        ),
    ]
